<a href="https://colab.research.google.com/github/nykim131/aice/blob/main/AICE_Pro_%EC%8B%9C%ED%97%98_%EB%A7%88%EC%8A%A4%ED%84%B0_%EB%B3%B5%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AICE Pro 자격인증 <font color=red>예상문항</font>**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!ls -ltr /content/drive/MyDrive/AICE/images/

total 8
drwx------ 2 root root 4096 Jun 20 05:56 train
drwx------ 2 root root 4096 Jun 20 05:56 test

#### **<span style="color:red">[유의사항]</span>**
- <span style="color:darkgreen">각 문항의 답안코드는 반드시 '# 여기에 답안코드를 작서하세요' 로 표시된 cell에 작성해야 합니다. </span>
- <span style="color:darkgreen">제공된 시험문항 cell을 삭제하거나 답안 위치가 아닌 다른 cell에 답안코드를 작성 시 채점되지 않습니다. </span>
- 시험 중에는 상단의 '임시저장' 버튼을 클릭하여 저장을 해주시고, 답안 제출시에는 '최종제출' 버튼을 클릭해주시기 바랍니다.
- 반드시 문제에 제시된 가이드를 읽고 답안 작성하세요.
- 문제에 변수명이 제시된 경우 반드시 해당 변수명을 사용하세요.
- 자격인증 문제에 제공된 데이터는 제 3자에게 공유하거나 개인적인 용도로 사용하는 등 외부로 유출할 수 없으며 유출로 인한 책임은 응시자 본인에게 있습니다.
- <font color=blue>**Copy & Paste를 위한 메모장, 노션 등을 사용할 경우 부정행위로 간주될 수 있습니다.**</font>
- <font color=blue>**생성형 AI를 활용한 검색은 부정행위로 별도의 경고조치 없이 적발 즉시 시험 중단될 수 있습니다.**</font>

### **1. 타이타닉 승객 데이터를 이용한 <span style="color:darkgreen">승객 생존 여부</span> 예측 문제**
- 타이타닉 승객 데이터를 읽어들여 데이터를 분석 및 전처리한 후 머신러닝 혹은 딥러닝으로 승객 생존 여부를 예측하고 결과를 분석하세요.
---

**[ 데이터 컬럼 설명 ]**
- PassengerId : 각 승객에게 주어진 고유 ID 번호
- Survived : 승객이 생존(Y)했는지 사망(N)했는지 여부
- Pclass : 선실 등급 (1:1등급, 2:2등급, 3:3등급)
- Name : 이름
- Sex : 승객의 성별
- Age : 승객의 나이
- SibSp : 형제자매/배우자의 수
- Parch : 부모/자녀의 수
- Ticket : 티켓 번호
- Fare : 팈켓에 대해 지불한 금액
- Cabin : 객실 카테고리
- Embarked : 승객이 탑승한 항구 (C=Cherbourg, Q=Queentown, S=Southampton)

**[ 문제 유의 사항 ]**
- 학습을 위한 데이터는 다음과 같다. (train_1.csv)
- 결과 예측을 위한 데이터는 다음과 같다. (test_1.csv)

- train_1.csv 데이터를 이용하여 승객의 생존 여부에 대한 학습을 진행하여 예측 모델을 생성한다.
- test_1.csv 데이터를 읽어와 위에서 생성된 모델을 활용하여 승객의 생존 여부(Y/N)를 예측하고 예측 값은 마지막 컬럼에 '생존여부'로 저장한다.
- 예측된 데이터의 정확도는 73 % 이상 되어야한다.

- 문제풀이를 위한 셀은 제한없이 생성 가능하다.
- 최종 모델의 저장은 pkl, h5 등 형식은 상관 없고 파일명은 '사번_문제번호.pkl(h5)' 와 같은 형식으로 저정한다.

In [173]:
# 여기에 답안코드를 작성하세요.
!ls -ltr /content/drive/MyDrive/AICE

import pandas as pd

train_ds1 = pd.read_csv('/content/drive/MyDrive/AICE/train_1.csv')
test_ds1 = pd.read_csv('/content/drive/MyDrive/AICE/test_1.csv')

total 20457
-rw------- 1 root root    62002 Jun 15 11:17 train_1.csv
-rw------- 1 root root     4164 Jun 15 11:17 test_3.csv
-rw------- 1 root root  5441518 Jun 15 11:17 test_2.csv
-rw------- 1 root root    28629 Jun 15 11:17 test_1.csv
-rw------- 1 root root 15406003 Jun 15 11:17 train_2.csv
drwx------ 4 root root     4096 Jun 20 05:56 images

In [174]:
train_ds1.head(5)
test_ds1.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [175]:
train_ds1.info()
train_ds1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    object
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [176]:
train_ds1.drop(['PassengerId','Name','Cabin', 'Ticket'], axis=1, inplace=True)
test_ds1.drop(['PassengerId','Name','Cabin', 'Ticket'], axis=1, inplace=True)

In [177]:
train_ds1['Age'] = train_ds1['Age'].fillna(train_ds1['Age'].mean())

In [178]:
train_ds1[train_ds1['Embarked'].isnull()==True]
train_ds1['Embarked'] = train_ds1['Embarked'].fillna('C')

In [179]:
test_ds1.info()
test_ds1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    418 non-null    int64
 1   Sex       418 non-null    object
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64
 4   Parch     418 non-null    int64
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [180]:
test_ds1['Age'] = test_ds1['Age'].fillna(test_ds1['Age'].mean())

In [181]:
test_ds1[test_ds1['Embarked']=='S']

     Pclass     Sex       Age  SibSp  Parch     Fare Embarked
1         3  female  47.00000      1      0   7.0000        S
3         3    male  27.00000      0      0   8.6625        S
4         3  female  22.00000      1      1  12.2875        S
5         3    male  14.00000      0      0   9.2250        S
7         2    male  26.00000      1      1  29.0000        S
..      ...     ...       ...    ...    ...      ...      ...
409       3  female   3.00000      1      1  13.7750        S
412       3  female  28.00000      0      0   7.7750        S
413       3    male  30.27259      0      0   8.0500        S
415       3    male  38.50000      0      0   7.2500        S
416       3    male  30.27259      0      0   8.0500        S

[270 rows x 7 columns]

In [182]:
test_ds1['Fare'] = test_ds1['Fare'].fillna(test_ds1[test_ds1['Embarked']=='S']['Fare'].mean())

In [183]:
train_ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    object
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

In [184]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()

train_ds1['Survived']=le1.fit_transform(train_ds1['Survived'])

In [188]:
train_ds1 = pd.get_dummies(train_ds1, columns=['Sex','Embarked'])
test_ds1 = pd.get_dummies(test_ds1, columns=['Sex','Embarked'])

In [189]:
train_ds1.info()
test_ds1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   Sex_female  891 non-null    bool
 7   Sex_male    891 non-null    bool
 8   Embarked_C  891 non-null    bool
 9   Embarked_Q  891 non-null    bool
 10  Embarked_S  891 non-null    bool
dtypes: bool(5), float64(2), int64(4)
memory usage: 46.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      418 non-null    int64
 1   Age         418 non-null    float64
 2   SibSp       418 non-null    int64
 3   Parch       418 non-null    int64
 4   Fare        418 non-null    float64
 5   Sex_female  418 non-null    bool
 6   Sex_male    418 non-null    bool
 7   Embarked_C  418 non-null    bool
 8   Embarked_Q  418 non-null    bool
 9   Embarked_S  418 non-null    bool
dtypes: bool(5), float64(2), int64(3)
memory usage: 18.5 KB

In [190]:
from sklearn.model_selection import train_test_split

X=train_ds1.drop('Survived', axis=1)
y=train_ds1['Survived']

# 데이터 분할
X_train, X_val, y_train, y_val = train_test_split(X, y, train_size=.8, stratify=y, random_state=2023)

In [191]:
from sklearn.preprocessing import MinMaxScaler

# 객체 생성
mms = MinMaxScaler()

# 스케일링 적용
X_train = mms.fit_transform(X_train)
X_val = mms.transform(X_val)

In [193]:
from sklearn.linear_model import LogisticRegression

# 모델 생성
lg = LogisticRegression(C=1.0, max_iter=1000)

# 모델 학습
lg.fit(X_train, y_train)

lg.score(X_val, y_val)

print('lg:', lg.score(X_val, y_val))

from sklearn.tree import DecisionTreeClassifier # 분류
from sklearn.tree import DecisionTreeRegressor # 회귀

# 모델 생성
dt = DecisionTreeClassifier(max_depth=5, random_state=2023)

# 모델 학습
dt.fit(X_train, y_train)

dt.score(X_val, y_val)

print('dt:', dt.score(X_val, y_val))

from sklearn.tree import DecisionTreeClassifier # 분류
from sklearn.tree import DecisionTreeRegressor # 회귀

# 모델 생성
dt = DecisionTreeClassifier(max_depth=5, random_state=2023)

# 모델 학습
dt.fit(X_train, y_train)

# 모델 평가
dt.score(X_val, y_val)

print('dt:', dt.score(X_val, y_val))

lg: 0.7653631284916201
dt: 0.7486033519553073
dt: 0.7486033519553073

In [203]:
result=lg.predict(test_ds1)
result = le1.inverse_transform(result)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [204]:
test_ds1['생존여부']=result

In [206]:
test_ds1

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,생존여부
0,3,34.50000,0,0,7.8292,False,True,False,True,False,N
1,3,47.00000,1,0,7.0000,True,False,False,False,True,N
2,2,62.00000,0,0,9.6875,False,True,False,True,False,N
3,3,27.00000,0,0,8.6625,False,True,False,False,True,N
4,3,22.00000,1,1,12.2875,True,False,False,False,True,N
...,...,...,...,...,...,...,...,...,...,...,...
413,3,30.27259,0,0,8.0500,False,True,False,False,True,N
414,1,39.00000,0,0,108.9000,True,False,True,False,False,N
415,3,38.50000,0,0,7.2500,False,True,False,False,True,N
416,3,30.27259,0,0,8.0500,False,True,False,False,True,N
417,3,30.27259,1,1,22.3583,False,True,True,False,False,N

### **2. 영화 리뷰 데이터를 이용한 <span style="color:darkgreen">감정</span> 예측 문제**
- 영화 리뷰 데이터를 읽어들여 데이터를 분석 및 전처리한 후 머신러닝 혹은 딥러닝으로 리뷰의 긍정/부정을 예측하고 결과를 분석하세요.
---

**[ 데이터 컬럼 설명 ]**
- id : 리뷰ID
- document : 고객 리뷰
- label : 고객의 감정 (긍정/부정)

**[ 문제 유의 사항 ]**
- 학습을 위한 데이터는 다음과 같다. (train_2.csv)
- 결과 예측을 위한 데이터는 다음과 같다. (test_2.csv)

- train_2.csv 데이터를 이용하여 고객 리뷰의 긍정/부정에 대한 학습을 진행하여 예측 모델을 생성한다.
- test_2.csv 데이터를 읽어와 위에서 생성된 모델을 활용하여 리뷰의 긍정/부정 여부를 예측하고 예측 값은 마지막 컬럼에 '감정'으로 저장한다.
- 예측된 데이터의 정확도는 60 % 이상 되어야한다.

- 문제풀이를 위한 셀은 제한없이 생성 가능하다.
- 최종 모델의 저장은 pkl, h5 등 형식은 상관 없고 파일명은 '사번_문제번호.pkl(h5)' 와 같은 형식으로 저정한다.

In [70]:
train_ds2 = pd.read_csv('/content/drive/MyDrive/AICE/train_2.csv')
test_ds2 = pd.read_csv('/content/drive/MyDrive/AICE/test_2.csv')

In [71]:
train_ds2.head(5)
test_ds2.head(5)

,Unnamed: 0,id,document,label
0,0,6270596,굳 ㅋ,긍정
1,1,9274899,GDNTOPCLASSINTHECLUB,부정
2,2,8544678,뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아,부정
3,3,6825595,지루하지는 않은데 완전 막장임... 돈주고 보기에는....,부정
4,4,6723715,3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??,부정

In [72]:
train_ds2['document'] = train_ds2['document'].str.replace('[^가-힣a-zA-Z0-9 ]','', regex=True)
train_ds2['document'] = train_ds2['document'].str.strip()

In [73]:
train_ds2.head(5)

         id                                           document label
0   9976970                                  아 더빙 진짜 짜증나네요 목소리    부정
1   3819312                         흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나    긍정
2  10265843                                  너무재밓었다그래서보는것을추천한다    부정
3   9045019                          교도소 이야기구먼 솔직히 재미는 없다평점 조정    부정
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...    긍정

In [74]:
train_ds2.isnull().sum()
train_ds2.dropna(inplace=True)

In [75]:
train_ds2.drop_duplicates(subset=['document'], inplace = True)

In [76]:
test_ds2['document'] = test_ds2['document'].str.replace('[^가-힣a-zA-Z0-9 ]','', regex=True)
test_ds2['document'] = test_ds2['document'].str.strip()

In [122]:
print(len(test_ds2))

49997

In [79]:
train_ds2['label'].value_counts()

label
부정    72107
긍정    71368
Name: count, dtype: int64

In [80]:
from sklearn.preprocessing import LabelEncoder

le2 = LabelEncoder()

In [81]:
train_ds2['label'] = le2.fit_transform(train_ds2['label'])

In [82]:
train_ds2['label']

0         1
1         0
2         1
3         1
4         0
         ..
149994    0
149995    1
149997    1
149998    0
149999    1
Name: label, Length: 143475, dtype: int64

In [83]:
from sklearn.model_selection import train_test_split
x_train_2, x_val_2, y_train_2, y_val_2 = train_test_split(train_ds2['document'], train_ds2['label'] , test_size=0.2, stratify=train_ds2['label'], random_state=41)

In [85]:
x_train_2.shape, x_val_2.shape, y_train_2.shape, y_val_2.shape

((114780,), (28695,), (114780,), (28695,))

In [93]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenizer 구현 : 단어 사전 만들기(fit_on_texts)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_train_2)

max_words = max(tokenizer.index_word) +1 # 총 단어 갯수 : 47,646

In [123]:
x_train_seq = tokenizer.texts_to_sequences(x_train_2)
x_val_seq = tokenizer.texts_to_sequences(x_val_2)
x_test_seq = tokenizer.texts_to_sequences(test_ds2['document'])

In [129]:
print(max(len(line) for line in x_train_seq))
print(max(len(line) for line in x_val_seq))
print(max(len(line) for line in x_test_seq))

max_len = max(len(line) for line in x_train_seq)

41
39
37

In [130]:
x_train_pad = pad_sequences(x_train_seq, maxlen=max_len)
x_val_pad = pad_sequences(x_val_seq, maxlen=max_len)
x_test_pad = pad_sequences(x_test_seq, maxlen=max_len)

In [101]:
print(x_train_pad[:1])
print(x_train_pad.shape, x_val_pad.shape)

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0   958 34064]]
(114780, 41) (28695, 41)

In [102]:
from tensorflow.keras.layers import Dense, Flatten, Conv1D, MaxPool2D
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, SimpleRNN, GRU
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

model2 = Sequential()

model2.add(Embedding(max_words, 32, input_length=max_len)) # 단어를 의미있는 32 차원으로 Vector 변경(Embedding)

# LSTM 모델
model2.add(LSTM(16, return_sequences=True))
model2.add(LSTM(16, return_sequences=True))
model2.add(Flatten())
model2.add(Dense(128, activation='swish'))
model2.add(Dense(32, activation='swish'))
model2.add(Dense(2, activation='softmax')) # 최종 6가지로 분류

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [104]:
model2.compile(loss = 'sparse_categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])
model2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [105]:
es = EarlyStopping(monitor='val_loss', patience=3, verbose=1)
checkpoint_path = 'tmp_checkpoint.h5'
cp = ModelCheckpoint(checkpoint_path, monitor='val_loss', verbose=1, save_best_only=True)

history = model2.fit(x_train_pad, y_train_2, epochs=50, batch_size=512,
                      validation_split=0.2, verbose =1, callbacks=[es, cp])

Epoch 1/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.6267 - loss: 0.6168
Epoch 1: val_loss improved from None to 0.42001, saving model to tmp_checkpoint.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 1: finished saving model to tmp_checkpoint.h5
180/180 ━━━━━━━━━━━━━━━━━━━━ 32s 151ms/step - accuracy: 0.7114 - loss: 0.5317 - val_accuracy: 0.7984 - val_loss: 0.4200
Epoch 2/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.9162 - loss: 0.2288
Epoch 2: val_loss did not improve from 0.42001
180/180 ━━━━━━━━━━━━━━━━━━━━ 21s 115ms/step - accuracy: 0.9197 - loss: 0.2205 - val_accuracy: 0.7958 - val_loss: 0.4726
Epoch 3/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.9804 - loss: 0.0658
Epoch 3: val_loss did not improve from 0.42001
180/180 ━━━━━━━━━━━━━━━━━━━━ 46s 143ms/step - accuracy: 0.9787 - loss: 0.0670 - val_accuracy: 0.7871 - val_loss: 0.6581
Epoch 4/50
180/180 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.9916 - loss: 0.0271
Epoch 4: val_loss did not improve from 0.42001
180/180 ━━━━━━━━━━━━━━━━━━━━ 44s 159ms/step - accuracy: 0.9902 - loss: 0.0299 - val_accuracy: 0.7835 - val_loss: 0.7780
Epoch 4: early stopping

In [107]:
model2.evaluate(x_val_pad, y_val_2)

897/897 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7881 - loss: 0.7837

[0.7836976647377014, 0.7881163954734802]

In [109]:
pred = np.argmax(model2.predict(x_test_pad))

897/897 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step

In [131]:
result = np.argmax(model2.predict(x_test_pad), axis=1)
result = le2.inverse_transform(result)

1563/1563 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step

In [132]:
print(len(result))

49997

In [133]:
test_ds2 = pd.read_csv('/content/drive/MyDrive/AICE/test_2.csv')

In [134]:
test_ds2['감정']=result

In [ ]:
# 여기에 답안코드를 작성하세요.

### **3. 이미지 데이터를 이용한 <span style="color:darkgreen">코끼리 종류</span> 예측 문제**
- 코끼리 이미지 데이터를 분석 및 전처리한 후 머신러닝 혹은 딥러닝으로 코끼리 종류를 예측하고 결과를 분석하세요.
---

**[ 데이터 설명 ]**
- train 데이터
1. /images/train/African : 아프리카 코끼리 이미지셋
2. /images/train/Asian   : 아시아 코끼리 이미지셋
- test 데이터
1. /images/test

**[ 문제 유의 사항 ]**
- train 데이터셋의 이미지를 이용하여 아프리카/아시아 코끼리 데이터에 대한 학습을 진행하여 예측 모델을 생성한다.
- 위에서 생성된 모델을 활용하여 test 데이터셋의 이미지들에 대해 아프리카 코끼리인지 아시아 코끼리인지에 대한 분류를 진행한다.
- 최종 결과 저장 파일명은 사번_문제번호.csv 로 저장한다. 컬럼1: Filename, 컬럼2: Result
- Result 분류 : African / Asian
- 예측된 데이터의 정확도는 70 % 이상 되어야한다.
- 문제풀이를 위한 셀은 제한없이 생성 가능하다.
- 최종 모델의 저장은 pkl, h5 등 형식은 상관 없고 파일명은 '사번_문제번호.pkl(h5)' 와 같은 형식으로 저정한다.

In [11]:
train_dir = ('/content/drive/MyDrive/AICE/images/train/')
test_dir = ('/content/drive/MyDrive/AICE/images/test/')

In [12]:
import tensorflow as tf

train_ds3 = tf.keras.utils.image_dataset_from_directory(
  train_dir,
  label_mode='binary',
  validation_split=0.2,
  subset="training",
  seed=42,
  shuffle=True,
  image_size=(224, 224),
  batch_size=32)

val_ds3 = tf.keras.utils.image_dataset_from_directory(
  train_dir,
  label_mode='binary',
  validation_split=0.2,
  subset="validation",
  seed=42,
  shuffle=True,
  image_size=(224, 224),
  batch_size=32)

Found 840 files belonging to 2 classes.
Using 672 files for training.
Found 840 files belonging to 2 classes.
Using 168 files for validation.

In [13]:
base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), weights='imagenet', include_top=False)

base_model.summary()

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5
9406464/9406464 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step

Model: "mobilenetv2_1.00_224"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv1 (Conv2D)      │ (None, 112, 112,  │        864 │ input_layer[0][0] │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bn_Conv1            │ (None, 112, 112,  │        128 │ Conv1[0][0]       │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv1_relu (ReLU)   │ (None, 112, 112,  │          0 │ bn_Conv1[0][0]    │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │        288 │ Conv1_relu[0][0]  │
│ (DepthwiseConv2D)   │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │        128 │ expanded_conv_de… │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_dept… │ (None, 112, 112,  │          0 │ expanded_conv_de… │
│ (ReLU)              │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_proj… │ (None, 112, 112,  │        512 │ expanded_conv_de… │
│ (Conv2D)            │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ expanded_conv_proj… │ (None, 112, 112,  │         64 │ expanded_conv_pr… │
│ (BatchNormalizatio… │ 16)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand      │ (None, 112, 112,  │      1,536 │ expanded_conv_pr… │
│ (Conv2D)            │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand_BN   │ (None, 112, 112,  │        384 │ block_1_expand[0… │
│ (BatchNormalizatio… │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_expand_relu │ (None, 112, 112,  │          0 │ block_1_expand_B… │
│ (ReLU)              │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_pad         │ (None, 113, 113,  │          0 │ block_1_expand_r… │
│ (ZeroPadding2D)     │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise   │ (None, 56, 56,    │        864 │ block_1_pad[0][0] │
│ (DepthwiseConv2D)   │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise_… │ (None, 56, 56,    │        384 │ block_1_depthwis… │
│ (BatchNormalizatio… │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_depthwise_… │ (None, 56, 56,    │          0 │ block_1_depthwis… │
│ (ReLU)              │ 96)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_project     │ (None, 56, 56,    │      2,304 │ block_1_depthwis… │
│ (Conv2D)            │ 24)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_1_project_BN  │ (None, 56, 56,    │         96 │ block_1_project[… │
│ (BatchNormalizatio… │ 24)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_expand      │ (None, 56, 56,    │      3,456 │ block_1_project_… │
│ (Conv2D)            │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_expand_BN   │ (None, 56, 56,    │        576 │ block_2_expand[0… │
│ (BatchNormalizatio… │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_expand_relu │ (None, 56, 56,    │          0 │ block_2_expand_B… │
│ (ReLU)              │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_depthwise   │ (None, 56, 56,    │      1,296 │ block_2_expand_r… │
│ (DepthwiseConv2D)   │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_depthwise_… │ (None, 56, 56,    │        576 │ block_2_depthwis… │
│ (BatchNormalizatio… │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_depthwise_… │ (None, 56, 56,    │          0 │ block_2_depthwis… │
│ (ReLU)              │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_project     │ (None, 56, 56,    │      3,456 │ block_2_depthwis… │
│ (Conv2D)            │ 24)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_project_BN  │ (None, 56, 56,    │         96 │ block_2_project[… │
│ (BatchNormalizatio… │ 24)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_2_add (Add)   │ (None, 56, 56,    │          0 │ block_1_project_… │
│                     │ 24)               │            │ block_2_project_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_expand      │ (None, 56, 56,    │      3,456 │ block_2_add[0][0] │
│ (Conv2D)            │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_expand_BN   │ (None, 56, 56,    │        576 │ block_3_expand[0… │
│ (BatchNormalizatio… │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_expand_relu │ (None, 56, 56,    │          0 │ block_3_expand_B… │
│ (ReLU)              │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_pad         │ (None, 57, 57,    │          0 │ block_3_expand_r… │
│ (ZeroPadding2D)     │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_depthwise   │ (None, 28, 28,    │      1,296 │ block_3_pad[0][0] │
│ (DepthwiseConv2D)   │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_depthwise_… │ (None, 28, 28,    │        576 │ block_3_depthwis… │
│ (BatchNormalizatio… │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_depthwise_… │ (None, 28, 28,    │          0 │ block_3_depthwis… │
│ (ReLU)              │ 144)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_project     │ (None, 28, 28,    │      4,608 │ block_3_depthwis… │
│ (Conv2D)            │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_3_project_BN  │ (None, 28, 28,    │        128 │ block_3_project[… │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_expand      │ (None, 28, 28,    │      6,144 │ block_3_project_… │
│ (Conv2D)            │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_expand_BN   │ (None, 28, 28,    │        768 │ block_4_expand[0… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_expand_relu │ (None, 28, 28,    │          0 │ block_4_expand_B… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_depthwise   │ (None, 28, 28,    │      1,728 │ block_4_expand_r… │
│ (DepthwiseConv2D)   │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_depthwise_… │ (None, 28, 28,    │        768 │ block_4_depthwis… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_depthwise_… │ (None, 28, 28,    │          0 │ block_4_depthwis… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_project     │ (None, 28, 28,    │      6,144 │ block_4_depthwis… │
│ (Conv2D)            │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_project_BN  │ (None, 28, 28,    │        128 │ block_4_project[… │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_4_add (Add)   │ (None, 28, 28,    │          0 │ block_3_project_… │
│                     │ 32)               │            │ block_4_project_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_expand      │ (None, 28, 28,    │      6,144 │ block_4_add[0][0] │
│ (Conv2D)            │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_expand_BN   │ (None, 28, 28,    │        768 │ block_5_expand[0… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_expand_relu │ (None, 28, 28,    │          0 │ block_5_expand_B… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_depthwise   │ (None, 28, 28,    │      1,728 │ block_5_expand_r… │
│ (DepthwiseConv2D)   │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_depthwise_… │ (None, 28, 28,    │        768 │ block_5_depthwis… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_depthwise_… │ (None, 28, 28,    │          0 │ block_5_depthwis… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_project     │ (None, 28, 28,    │      6,144 │ block_5_depthwis… │
│ (Conv2D)            │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_project_BN  │ (None, 28, 28,    │        128 │ block_5_project[… │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_5_add (Add)   │ (None, 28, 28,    │          0 │ block_4_add[0][0… │
│                     │ 32)               │            │ block_5_project_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_expand      │ (None, 28, 28,    │      6,144 │ block_5_add[0][0] │
│ (Conv2D)            │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_expand_BN   │ (None, 28, 28,    │        768 │ block_6_expand[0… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_expand_relu │ (None, 28, 28,    │          0 │ block_6_expand_B… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_pad         │ (None, 29, 29,    │          0 │ block_6_expand_r… │
│ (ZeroPadding2D)     │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_depthwise   │ (None, 14, 14,    │      1,728 │ block_6_pad[0][0] │
│ (DepthwiseConv2D)   │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_depthwise_… │ (None, 14, 14,    │        768 │ block_6_depthwis… │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_depthwise_… │ (None, 14, 14,    │          0 │ block_6_depthwis… │
│ (ReLU)              │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_project     │ (None, 14, 14,    │     12,288 │ block_6_depthwis… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_6_project_BN  │ (None, 14, 14,    │        256 │ block_6_project[… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_expand      │ (None, 14, 14,    │     24,576 │ block_6_project_… │
│ (Conv2D)            │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_expand_BN   │ (None, 14, 14,    │      1,536 │ block_7_expand[0… │
│ (BatchNormalizatio… │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_expand_relu │ (None, 14, 14,    │          0 │ block_7_expand_B… │
│ (ReLU)              │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_depthwise   │ (None, 14, 14,    │      3,456 │ block_7_expand_r… │
│ (DepthwiseConv2D)   │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_depthwise_… │ (None, 14, 14,    │      1,536 │ block_7_depthwis… │
│ (BatchNormalizatio… │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_depthwise_… │ (None, 14, 14,    │          0 │ block_7_depthwis… │
│ (ReLU)              │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_project     │ (None, 14, 14,    │     24,576 │ block_7_depthwis… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_project_BN  │ (None, 14, 14,    │        256 │ block_7_project[… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_7_add (Add)   │ (None, 14, 14,    │          0 │ block_6_project_… │
│                     │ 64)               │            │ block_7_project_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_expand      │ (None, 14, 14,    │     24,576 │ block_7_add[0][0] │
│ (Conv2D)            │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_expand_BN   │ (None, 14, 14,    │      1,536 │ block_8_expand[0… │
│ (BatchNormalizatio… │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_expand_relu │ (None, 14, 14,    │          0 │ block_8_expand_B… │
│ (ReLU)              │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_depthwise   │ (None, 14, 14,    │      3,456 │ block_8_expand_r… │
│ (DepthwiseConv2D)   │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_depthwise_… │ (None, 14, 14,    │      1,536 │ block_8_depthwis… │
│ (BatchNormalizatio… │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_depthwise_… │ (None, 14, 14,    │          0 │ block_8_depthwis… │
│ (ReLU)              │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_project     │ (None, 14, 14,    │     24,576 │ block_8_depthwis… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_project_BN  │ (None, 14, 14,    │        256 │ block_8_project[… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_8_add (Add)   │ (None, 14, 14,    │          0 │ block_7_add[0][0… │
│                     │ 64)               │            │ block_8_project_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_9_expand      │ (None, 14, 14,    │     24,576 │ block_8_add[0][0] │
│ (Conv2D)            │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_9_expand_BN   │ (None, 14, 14,    │      1,536 │ block_9_expand[0… │
│ (BatchNormalizatio… │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_9_expand_relu │ (None, 14, 14,    │          0 │ block_9_expand_B… │
│ (ReLU)              │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_9_depthwise   │ (None, 14, 14,    │      3,456 │ block_9_expand_r… │
│ (DepthwiseConv2D)   │ 384)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ block_9_depthwise_… │ (None, 14, 14,    │      1,536 │ block_9_depthwis… │

 Total params: 2,257,984 (8.61 MB)

 Trainable params: 2,223,872 (8.48 MB)

 Non-trainable params: 34,112 (133.25 KB)

In [16]:
# weight freeze
base_model.trainable = False

inputs = tf.keras.Input(shape=(224, 224, 3))
x = tf.keras.layers.Rescaling(1./127.5, offset=-1)(inputs) # rescaling
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)  # 3차원(7, 7, 1280) --> 1차원(1280)으로 줄이기 : GlobalAveragePooling2D
output = tf.keras.layers.Dense(2, activation='softmax')(x)

model3 = tf.keras.Model(inputs=inputs, outputs=output)
model3.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ rescaling_1 (Rescaling)         │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_224            │ (None, 7, 7, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d_1      │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │         2,562 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,260,546 (8.62 MB)

 Trainable params: 2,562 (10.01 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

In [17]:
model3.compile(optimizer=tf.keras.optimizers.Adam(0.001),  # Optimization
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])             # Metrics / Accuracy

In [18]:
# step 3 Callback
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

## EarlyStopping
es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=3)

## ModelCheckpoint
checkpoint_path = "my_checkpoint.h5"
checkpoint = ModelCheckpoint(filepath=checkpoint_path,
                             save_best_only=True,
                             monitor='val_loss',
                             verbose=1)

In [24]:
# 모델 학습(fit)
history = model3.fit(
    train_ds3,
    validation_data = val_ds3,
    epochs=100,
    callbacks=[es, checkpoint]
)

Epoch 1/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 898ms/step - accuracy: 0.7673 - loss: 0.4995
Epoch 1: val_loss improved from 0.54992 to 0.54762, saving model to my_checkpoint.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 1: finished saving model to my_checkpoint.h5
21/21 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - accuracy: 0.7589 - loss: 0.5108 - val_accuracy: 0.7619 - val_loss: 0.5476
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 948ms/step - accuracy: 0.7809 - loss: 0.4883
Epoch 2: val_loss did not improve from 0.54762
21/21 ━━━━━━━━━━━━━━━━━━━━ 37s 1s/step - accuracy: 0.7827 - loss: 0.4853 - val_accuracy: 0.7381 - val_loss: 0.5505
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 930ms/step - accuracy: 0.7948 - loss: 0.4658
Epoch 3: val_loss did not improve from 0.54762
21/21 ━━━━━━━━━━━━━━━━━━━━ 25s 1s/step - accuracy: 0.7946 - loss: 0.4628 - val_accuracy: 0.7440 - val_loss: 0.5542
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 0.7869 - loss: 0.4547
Epoch 4: val_loss did not improve from 0.54762
21/21 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - accuracy: 0.7976 - loss: 0.4486 - val_accuracy: 0.7440 - val_loss: 0.5598
Epoch 4: early stopping

In [25]:
model3.evaluate(val_ds3)

6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 695ms/step - accuracy: 0.7440 - loss: 0.5598

[0.5598088502883911, 0.7440476417541504]

In [28]:
import os
import numpy as np

result=[]

from keras.preprocessing import image
file_name=os.listdir(test_dir)

for item in file_name :
  img = image.load_img(test_dir+item, target_size=(224,224))
  x=image.img_to_array(img)
  x=np.expand_dims(x, axis=0)
  preds = np.argmax(model3.predict(x))
  result.append([item,train_ds3.class_names[preds]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

In [29]:
result

[['af_te3.jpg', 'African'],
 ['af_te26.jpg', 'African'],
 ['af_te11.jpg', 'African'],
 ['af_te17.jpg', 'African'],
 ['af_te22.jpg', 'African'],
 ['af_te20.jpg', 'African'],
 ['af_te21.jpg', 'Asian'],
 ['af_te16.jpg', 'African'],
 ['af_te32.jpg', 'African'],
 ['af_te15.jpg', 'African'],
 ['af_te1.jpg', 'African'],
 ['af_te28.jpg', 'African'],
 ['af_te30.jpg', 'Asian'],
 ['af_te25.jpg', 'African'],
 ['af_te10.jpg', 'African'],
 ['af_te27.jpg', 'African'],
 ['af_te13.jpg', 'African'],
 ['af_te23.jpg', 'African'],
 ['af_te19.jpg', 'African'],
 ['af_te31.jpg', 'Asian'],
 ['af_te24.jpg', 'African'],
 ['af_te12.jpg', 'African'],
 ['af_te33.jpg', 'African'],
 ['af_te14.jpg', 'African'],
 ['af_te2.jpg', 'Asian'],
 ['af_te29.jpg', 'African'],
 ['af_te18.jpg', 'African'],
 ['af_te66.jpg', 'Asian'],
 ['af_te42.jpg', 'African'],
 ['af_te37.jpg', 'African'],
 ['af_te71.jpg', 'African'],
 ['af_te49.jpg', 'African'],
 ['af_te67.jpg', 'African'],
 ['af_te64.jpg', 'African'],
 ['af_te7.jpg', 'African'],
 ['af_te44.jpg', 'African'],
 ['af_te43.jpg', 'African'],
 ['af_te47.jpg', 'African'],
 ['af_te78.jpg', 'African'],
 ['af_te63.jpg', 'African'],
 ['af_te38.jpg', 'Asian'],
 ['af_te34.jpg', 'African'],
 ['af_te74.jpg', 'African'],
 ['af_te77.jpg', 'African'],
 ['af_te8.jpg', 'African'],
 ['af_te70.jpg', 'African'],
 ['af_te59.jpg', 'African'],
 ['af_te69.jpg', 'African'],
 ['af_te56.jpg', 'African'],
 ['af_te79.jpg', 'African'],
 ['af_te68.jpg', 'African'],
 ['af_te39.jpg', 'Asian'],
 ['af_te57.jpg', 'African'],
 ['af_te45.jpg', 'Asian'],
 ['af_te62.jpg', 'African'],
 ['af_te54.jpg', 'African'],
 ['af_te61.jpg', 'African'],
 ['af_te58.jpg', 'African'],
 ['af_te50.jpg', 'African'],
 ['af_te35.jpg', 'Asian'],
 ['af_te76.jpg', 'African'],
 ['af_te53.jpg', 'African'],
 ['af_te6.jpg', 'African'],
 ['af_te51.jpg', 'Asian'],
 ['af_te52.jpg', 'African'],
 ['af_te72.jpg', 'Asian'],
 ['af_te48.jpg', 'African'],
 ['af_te36.jpg', 'African'],
 ['af_te41.jpg', 'African'],
 ['af_te5.jpg', 'African'],
 ['af_te55.jpg', 'Asian'],
 ['af_te75.jpg', 'Asian'],
 ['af_te4.jpg', 'African'],
 ['af_te65.jpg', 'Asian'],
 ['af_te73.jpg', 'African'],
 ['af_te46.jpg', 'African'],
 ['af_te40.jpg', 'African'],
 ['as_te14.jpg', 'African'],
 ['as_te15.jpg', 'African'],
 ['af_te94.jpg', 'African'],
 ['as_te29.jpg', 'African'],
 ['as_te10.jpg', 'Asian'],
 ['as_te3.jpg', 'African'],
 ['af_te99.jpg', 'African'],
 ['af_te93.jpg', 'African'],
 ['as_te25.jpg', 'Asian'],
 ['af_te97.jpg', 'African'],
 ['af_te87.jpg', 'African'],
 ['as_te30.jpg', 'Asian'],
 ['as_te11.jpg', 'Asian'],
 ['as_te24.jpg', 'African'],
 ['as_te20.jpg', 'Asian'],
 ['af_te98.jpg', 'Asian'],
 ['as_te19.jpg', 'Asian'],
 ['as_te22.jpg', 'Asian'],
 ['af_te91.jpg', 'African'],
 ['as_te26.jpg', 'Asian'],
 ['as_te21.jpg', 'Asian'],
 ['af_te83.jpg', 'African'],
 ['af_te92.jpg', 'Asian'],
 ['af_te95.jpg', 'Asian'],
 ['af_te88.jpg', 'African'],
 ['af_te96.jpg', 'African'],
 ['af_te80.jpg', 'African'],
 ['as_te1.jpg', 'Asian'],
 ['as_te28.jpg', 'Asian'],
 ['af_te9.jpg', 'African'],
 ['as_te27.jpg', 'Asian'],
 ['af_te81.jpg', 'African'],
 ['af_te86.jpg', 'African'],
 ['as_te16.jpg', 'African'],
 ['as_te2.jpg', 'Asian'],
 ['af_te82.jpg', 'African'],
 ['af_te85.jpg', 'African'],
 ['af_te84.jpg', 'African'],
 ['as_te31.jpg', 'Asian'],
 ['as_te13.jpg', 'Asian'],
 ['as_te23.jpg', 'Asian'],
 ['as_te18.jpg', 'Asian'],
 ['af_te90.jpg', 'African'],
 ['as_te7.jpg', 'Asian'],
 ['as_te45.jpg', 'Asian'],
 ['as_te40.jpg', 'Asian'],
 ['as_te51.jpg', 'Asian'],
 ['as_te59.jpg', 'Asian'],
 ['as_te53.jpg', 'Asian'],
 ['as_te41.jpg', 'African'],
 ['as_te46.jpg', 'Asian'],
 ['as_te42.jpg', 'Asian'],
 ['as_te70.jpg', 'Asian'],
 ['as_te61.jpg', 'Asian'],
 ['as_te4.jpg', 'Asian'],
 ['as_te63.jpg', 'Asian'],
 ['as_te52.jpg', 'Asian'],
 ['as_te37.jpg', 'African'],
 ['as_te58.jpg', 'Asian'],
 ['as_te6.jpg', 'Asian'],
 ['as_te35.jpg', 'Asian'],
 ['as_te47.jpg', 'African'],
 ['as_te50.jpg', 'Asian'],
 ['as_te34.jpg', 'Asian'],
 ['as_te54.jpg', 'Asian'],
 ['as_te56.jpg', 'Asian'],
 ['as_te65.jpg', 'Asian'],
 ['as_te5.jpg', 'Asian'],
 ['as_te36.jpg', 'Asian'],
 ['as_te39.jpg', 'Asian'],
 ['as_te43.jpg', 'Asian'],
 ['as_te44.jpg', 'Asian'],
 ['as_te68.jpg', 'Asian'],
 ['as_te62.jpeg', 'Asian'],
 ['as_te67.jpg', 'Asian'],
 ['as_te48.jpg', 'Asian'],
 ['as_te32.jpg', 'Asian'],
 ['as_te38.jpg', 'Asian'],
 ['as_te60.jpg', 'African'],
 ['as_te57.jpg', 'African'],
 ['as_te55.jpg', 'Asian'],
 ['as_te64.jpg', 'Asian'],
 ['as_te49.jpg', 'Asian'],
 ['as_te69.jpg', 'Asian'],
 ['as_te66.jpg', 'Asian'],
 ['as_te74.jpg', 'African'],
 ['as_te71.jpg', 'Asian'],
 ['as_te97.jpg', 'Asian'],
 ['as_te92.jpg', 'African'],
 ['as_te89.jpg', 'Asian'],
 ['as_te83.jpg', 'African'],
 ['as_te73.jpg', 'African'],
 ['as_te8.jpg', 'Asian'],
 ['as_te79.jpg', 'Asian'],
 ['as_te95.jpg', 'Asian'],
 ['as_te9.jpg', 'Asian'],
 ['as_te86.jpg', 'Asian'],
 ['as_te75.png', 'African'],
 ['as_te93.jpg', 'Asian'],
 ['as_te99.jpg', 'Asian'],
 ['as_te82.jpg', 'Asian'],
 ['as_te98.jpg', 'Asian'],
 ['as_te81.jpg', 'Asian'],
 ['as_te80.jpg', 'Asian'],
 ['as_te84.jpg', 'Asian'],
 ['as_te91.jpg', 'Asian'],
 ['as_te76.jpg', 'Asian'],
 ['as_te87.jpg', 'Asian'],
 ['as_te94.jpg', 'Asian'],
 ['as_te88.jpg', 'Asian'],
 ['as_te96.jpg', 'Asian']]

In [35]:

result_df = pd.DataFrame(result, columns=['FileName', 'result'])

In [37]:
result_df.to_csv('010_3.csv')

In [39]:
import joblib
joblib.dump(model3,'010_3.h1')

['010_3.h1']